kind: pipeline
name: gradle-check-11

steps:
  - name: gradle check
    image: adoptopenjdk:11-jdk-hotspot
    commands:
      - ./gradlew check --scan -x yarnJest


---

kind: pipeline
name: gradle-check-15

steps:
  - name: gradle check
    image: adoptopenjdk:15-jdk-hotspot
    commands:
      - ./gradlew check --scan -x yarnJest
