kind: pipeline
name: gradle-check-11

steps:
  - name: gradle check
    image: gradle:7.5.0-jdk11
    commands:
      - ./gradlew check --scan
    environment:
      ORG_GRADLE_PROJECT_HelloGithubPackageUsername:
        from_secret: ORG_GRADLE_PROJECT_HelloGithubPackageUsername
      ORG_GRADLE_PROJECT_HelloGithubPackagePassword:
        from_secret: ORG_GRADLE_PROJECT_HelloGithubPackagePassword


---

kind: pipeline
name: gradle-check-17

steps:
  - name: gradle check
    image: gradle:7.5.0-jdk17
    commands:
      - ./gradlew check --scan
    environment:
      ORG_GRADLE_PROJECT_HelloGithubPackageUsername:
        from_secret: ORG_GRADLE_PROJECT_HelloGithubPackageUsername
      ORG_GRADLE_PROJECT_HelloGithubPackagePassword:
        from_secret: ORG_GRADLE_PROJECT_HelloGithubPackagePassword
