version: '3'

networks:
  app:
  ci:
  monitoring:

services:
  nginx:
    container_name: hello-nginx
    image: nginx
    ports:
      - "80:80"
    networks:
      - app
  redis:
    container_name: hello-redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app
  mysql:
    container_name: hello-mysql
    image: mysql
    volumes:
      - ./docker/mysql/datadir:/var/lib/mysql
      - ./subprojects/hello-mybatis/sql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      # see :hello-mybatis
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: hello_database
      MYSQL_USER: hello_user
      MYSQL_PASSWORD: hello_password
    networks:
      - app
    command: --default-authentication-plugin=mysql_native_password
  zipkin:
    container_name: hello-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - monitoring
  centraldogma:
    container_name: hello-centraldogma
    image: line/centraldogma
    volumes:
      - ./docker/centraldogma/datadir:/opt/centraldogma/data
    ports:
      - "36462:36462"
    networks:
      - app
  fluentd:
    container_name: hello-fluentd
    image: fluentd
    volumes:
      - ./docker/fluentd/log:/fluentd/log
    ports:
      - "24224:24224"
    networks:
      - app
  teamcity-server:
    container_name: hello-teamcity-server
    image: jetbrains/teamcity-server
    volumes:
      - ./docker/teamcity_server/datadir:/data/teamcity_server/datadir
      - ./docker/teamcity_server/logs:/opt/teamcity/logs
    ports:
      - "8111:8111"
    networks:
      - ci
  teamcity-agent:
    container_name: hello-teamcity-agent
    image: jetbrains/teamcity-agent
    environment:
      SERVER_URL: http://teamcity-server:8111
    networks:
      - ci
  teamcity-agent-java11:
    build:
      context: docker/teamcity-agent-java11
      dockerfile: Dockerfile
    container_name: hello-teamcity-agent-java11
    environment:
      SERVER_URL: http://teamcity-server:8111
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      TEAMCITY_JRE: /usr/lib/jvm/java-11-openjdk-amd64
    networks:
      - ci
  jenkins:
    container_name: hello-jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "8112:8080"
      - "50000:50000"
    volumes:
      - ./docker/jenkins/jenkins_home:/var/jenkins_home
    networks:
      - ci
  jenkins-agent:
    container_name: hello-jenkins-agent
    image: jenkins/ssh-agent:jdk11
    environment:
      JENKINS_AGENT_SSH_PUBKEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/lGrmR+Q+XoOnyXK1Ip4VzI/P7WJdnA2oJQPF8QcUzqpQPrEgB4MY1knnDgL2X21IIl7Qjbrgw2pMFecG15W8xKk3R5a1IGUCBHovmOIKv6bUqnidKq5vWVhOcZpzA1bRFwDuHaquCWHkFrHHq/IUaI4/UllCZ7dBrDdHTXWqWL9RMbZc5H94yjU3RFUgK7MRHi4oD4Ya4LK2UDyIVKmBaktO5hCOM6+Ado11KAPdmnj5P2rquHp/OhGIoV1P4B21v4YjVCFMbz/16RgjjWSTOdJc/jmwkxDIglbT+C6r8A0QBtOq9zY25L3fXp+3BdoJFFU8ivf0E9sW67g1G0qlSUAvy3n4r1DylXH8+F96iByCuQ9HLSIuhCos7oruKQgIjLgH6vxnGILqR+gpIKvNIADAralYG7ZpdYin6mqsvm3dg52scpFuqn1z+eWb6U4pmUgxlDfay0Iw+k9ZWwc1QQdnI+94MDm89LeraRR0+eLddknyXlT85fzT4ZWpyos=
    networks:
      - ci
  grafana:
    container_name: hello-grafana
    image: grafana/grafana
    volumes:
      - ./docker/grafana/datadir:/var/lib/grafana
    ports:
    - "3000:3000"
    networks:
      - monitoring
  grafana-loki:
    container_name: hello-grafana-loki
    image: grafana/loki
    ports:
      - "3100:3100"
    networks:
      - monitoring
  intellij-idea:
    container_name: hello-intellij-idea
    image: registry.jetbrains.team/p/prj/containers/projector-idea-c
    ports:
      - "8887:8887"
  quodana:
    container_name: hello-quodana
    image: jetbrains/qodana-jvm
    ports:
      - "8200:8080"
    volumes:
      - ./:/data/project/
      - ./results/:/data/results/
