version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
  redis:
    image: redis
    ports:
      - 6379:6379
  mysql:
    image: mysql
    ports:
      - 3316:3316
    environment:
      MYSQL_ROOT_PASSWORD: password
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
