version: 2
jobs:
  gradle-check:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run: ./gradlew check
      - store_test_results:
          path: build/test-results/junit/
      - store_artifacts:
          path: build/reports/tests/test/

workflows:
  version: 2
  workflow:
    jobs:
      - gradle-check
