version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

workflows:
  version: 2
  workflow:
    jobs:
      - gradle/test:
          command: check --no-daemon --scan
          filters:
            branches:
              only: master
