version: 2.1

# testcontainers
machine: true

orbs:
  gradle: circleci/gradle@2.2.0

workflows:
  version: 2
  workflow:
    jobs:
      - gradle/test:
          store_artifacts: build/test-results/tests/test
          test_results_path: build/report/tests/test
          matrix:
            parameters:
              tags: [ "11.0", "15.0" ]
          filters:
            branches:
              only: master
