version: 2.1

## cache strategy
# gradle build cache
# gradle wrapper
# gradle node plugin's binary files

commands:
  restore_gradle_wrapper_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

  save_gradle_wrapper_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          when: always

  restore_gradle_caches:
    parameters:
      jdk-version:
        type: string
        default: "11.0"
    steps:
      - restore_cache:
          keys:
            - v1-gradle-caches-<< parameters.jdk-version >>-{{ .Branch }}-{{ .Revision }}
            - v1-gradle-caches-<< parameters.jdk-version >>-{{ .Branch }}-
            - v1-gradle-caches-<< parameters.jdk-version >>-

# https://docs.gradle.org/current/userguide/travis-ci.html
  run_before_gradle_caches:
    steps:
    - run:
        name: run before gradle caches
        command: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -rf ~/.gradle/caches/*/plugin-resolution/

  save_gradle_caches:
    parameters:
      jdk-version:
        type: string
        default: "11.0"
    steps:
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-caches-<< parameters.jdk-version >>-{{ .Branch }}-{{ .Revision }}

  restore_yarn_cache:
    parameters:
      jdk-version:
        type: string
        default: "11.0"
    steps:
      - restore_cache:
          keys:
          - v1-yarn-<< parameters.jdk-version >>-{{ .Branch }}-{{ .Revision }}
          - v1-yarn-<< parameters.jdk-version >>-{{ .Branch }}-
          - v1-yarn-<< parameters.jdk-version >>-

  save_yarn_cache:
    parameters:
      jdk-version:
        type: string
        default: "11.0"
    steps:
      - save_cache:
          paths:
            # yarn cache config
            - ~/.yarn/cache/v6
          key: v1-yarn-<< parameters.jdk-version >>-{{ .Branch }}-{{ .Revision }}

jobs:
  gradle-check:
    parameters:
      jdk-version:
        type: string
        default: "11.0"

    # testcontainers
    machine:
      image: ubuntu-2004:202104-01

    steps:
      - checkout
      - restore_gradle_wrapper_cache
      - restore_gradle_caches
      - restore_yarn_cache
      - restore_cache:
          keys:
            - v1-gradle-kotlinjs-<< parameters.jdk-version >>-{{ .Branch }}-{{ .Revision }}
            - v1-gradle-kotlinjs-<< parameters.jdk-version >>-{{ .Branch }}-
            - v1-gradle-kotlinjs-<< parameters.jdk-version >>-
      - run: ./gradlew check --scan
      - save_gradle_wrapper_cache
      - run_before_gradle_caches
      - save_gradle_caches
      - save_yarn_cache
      - save_cache:
          paths:
            - build/js
          key: v1-gradle-kotlinjs-<< parameters.jdk-version >>-{{ .Branch }}-{{ .Revision }}
      - store_test_results:
          path: build/test-results/junit/
      - store_artifacts:
          path: build/reports/tests/test/

workflows:
  version: 2
  workflow:
    jobs:
      - gradle-check:
          matrix:
            parameters:
              jdk-version: [ "11.0" ]
          filters:
            branches:
              only: master
