version: 2
jobs:
  gradle-check:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run: ./gradlew check

workflows:
  version: 2
  workflow:
    jobs:
      - gradle-check
