version: 2.1

## cache strategy
# gradle build cache
# gradle wrapper
# gradle node plugin's binary files

restore_gradle_wrapper_cache: &restore_gradle_wrapper_cache
  restore_cache:
    key: v0-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

save_gradle_wrapper_cache: &save_gradle_wrapper_cache
  save_cache:
    paths:
      - ~/.gradle/wrapper
    key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
    when: always

restore_gradle_node_plugin_cache: &restore_gradle_node_plugin_cache
  restore_cache:
    keys:
      - v1-gradle-node-plugin-{{ .Branch }}-{{ .Revision }}
      - v1-gradle-node-plugin-{{ .Branch }}-
      - v1-gradle-node-plugin-

save_gradle_node_plugin_cache: &save_gradle_node_plugin_cache
  save_cache:
    paths:
      - ~/.gradle/nodejs
      - ~/.gradle/yarn
      - ~/.yarn/cache/v6
    key: v1-gradle-node-plugin-{{ .Branch }}-{{ .Revision }}

jobs:
  gradle-check:
    parameters:
      jdk-version:
        type: string
        default: "11.0"

    # testcontainers
    machine:
      image: ubuntu-2004:202104-01

    steps:
      - checkout
      - <<: *restore_gradle_wrapper_cache
      - restore_cache:
          keys:
            - v1-gradle-cache-{{ .Branch }}-{{ .Revision }}
            - v1-gradle-cache-{{ .Branch }}-
            - v1-gradle-cache-
      - restore_cache:
          keys:
            - v1-gradle-build-cache-{{ .Branch }}-{{ .Revision }}
            - v1-gradle-build-cache-{{ .Branch }}-
            - v1-gradle-build-cache-
      - <<: *restore_gradle_node_plugin_cache
      - restore_cache:
          keys:
            - v1-gradle-kotlinjs-{{ .Branch }}-{{ .Revision }}
            - v1-gradle-kotlinjs-{{ .Branch }}-
            - v1-gradle-kotlinjs-
      - run: ./gradlew check
      - <<: *save_gradle_wrapper_cache
      - save_cache:
          paths:
            - ~/.gradle/caches/module-2
            - ~/.gradle/jdks
          key: v1-gradle-cache-{{ .Branch }}-{{ .Revision }}
      - <<: *save_gradle_node_plugin_cache
      - save_cache:
          paths:
            - ~/.gradle/caches/build-cache-1
          key: v1-gradle-build-cache-{{ .Branch }}-{{ .Revision }}
      - save_cache:
          paths:
            - build/js
          key: v1-gradle-kotlinjs-{{ .Branch }}-{{ .Revision }}
      - store_test_results:
          path: build/test-results/junit/
      - store_artifacts:
          path: build/reports/tests/test/

workflows:
  version: 2
  workflow:
    jobs:
      - gradle-check:
          matrix:
            parameters:
              jdk-version: [ "11.0", "15.0" ]
          filters:
            branches:
              only: master
