version: 2.1

# testcontainers
machine: true

orbs:
  gradle: circleci/gradle@2.2.0

workflows:
  workflow:
    jobs:
      - gradle/test:
          matrix:
            parameters:
              tag: [ "11.0", "15.0" ]
          filters:
            branches:
              only: master
