//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.25 at 08:55:55 AM UTC 
//


package ties.crs.v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ties.commontypesfatcacrs.v2.MonAmntType;
import ties.crsstf.v5.DocSpecType;


/**
 * <p>Java class for CorrectableAccountReport_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CorrectableAccountReport_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocSpec" type="{urn:oecd:ties:crsstf:v5}DocSpec_Type"/&gt;
 *         &lt;element name="AccountNumber" type="{urn:oecd:ties:crs:v2}FIAccountNumber_Type"/&gt;
 *         &lt;element name="AccountHolder" type="{urn:oecd:ties:crs:v2}AccountHolder_Type"/&gt;
 *         &lt;element name="ControllingPerson" type="{urn:oecd:ties:crs:v2}ControllingPerson_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="AccountBalance" type="{urn:oecd:ties:commontypesfatcacrs:v2}MonAmnt_Type"/&gt;
 *         &lt;element name="Payment" type="{urn:oecd:ties:crs:v2}Payment_Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorrectableAccountReport_Type", propOrder = {
    "docSpec",
    "accountNumber",
    "accountHolder",
    "controllingPerson",
    "accountBalance",
    "payment"
})
public class CorrectableAccountReportType {

    @XmlElement(name = "DocSpec", required = true)
    protected DocSpecType docSpec;
    @XmlElement(name = "AccountNumber", required = true)
    protected FIAccountNumberType accountNumber;
    @XmlElement(name = "AccountHolder", required = true)
    protected AccountHolderType accountHolder;
    @XmlElement(name = "ControllingPerson")
    protected List<ControllingPersonType> controllingPerson;
    @XmlElement(name = "AccountBalance", required = true)
    protected MonAmntType accountBalance;
    @XmlElement(name = "Payment")
    protected List<PaymentType> payment;

    /**
     * Gets the value of the docSpec property.
     * 
     * @return
     *     possible object is
     *     {@link DocSpecType }
     *     
     */
    public DocSpecType getDocSpec() {
        return docSpec;
    }

    /**
     * Sets the value of the docSpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocSpecType }
     *     
     */
    public void setDocSpec(DocSpecType value) {
        this.docSpec = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link FIAccountNumberType }
     *     
     */
    public FIAccountNumberType getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link FIAccountNumberType }
     *     
     */
    public void setAccountNumber(FIAccountNumberType value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the accountHolder property.
     * 
     * @return
     *     possible object is
     *     {@link AccountHolderType }
     *     
     */
    public AccountHolderType getAccountHolder() {
        return accountHolder;
    }

    /**
     * Sets the value of the accountHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountHolderType }
     *     
     */
    public void setAccountHolder(AccountHolderType value) {
        this.accountHolder = value;
    }

    /**
     * Gets the value of the controllingPerson property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controllingPerson property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControllingPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControllingPersonType }
     * 
     * 
     */
    public List<ControllingPersonType> getControllingPerson() {
        if (controllingPerson == null) {
            controllingPerson = new ArrayList<ControllingPersonType>();
        }
        return this.controllingPerson;
    }

    /**
     * Gets the value of the accountBalance property.
     * 
     * @return
     *     possible object is
     *     {@link MonAmntType }
     *     
     */
    public MonAmntType getAccountBalance() {
        return accountBalance;
    }

    /**
     * Sets the value of the accountBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonAmntType }
     *     
     */
    public void setAccountBalance(MonAmntType value) {
        this.accountBalance = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentType }
     * 
     * 
     */
    public List<PaymentType> getPayment() {
        if (payment == null) {
            payment = new ArrayList<PaymentType>();
        }
        return this.payment;
    }

}
