//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.25 at 08:55:55 AM UTC 
//


package ties.crs.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CrsMessageTypeIndic_EnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CrsMessageTypeIndic_EnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CRS701"/&gt;
 *     &lt;enumeration value="CRS702"/&gt;
 *     &lt;enumeration value="CRS703"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CrsMessageTypeIndic_EnumType")
@XmlEnum
public enum CrsMessageTypeIndicEnumType {


    /**
     * The message contains new information
     * 
     */
    @XmlEnumValue("CRS701")
    CRS_701("CRS701"),

    /**
     * The message contains corrections for previously sent information
     * 
     */
    @XmlEnumValue("CRS702")
    CRS_702("CRS702"),

    /**
     * The message advises there is no data to report
     * 
     */
    @XmlEnumValue("CRS703")
    CRS_703("CRS703");
    private final String value;

    CrsMessageTypeIndicEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CrsMessageTypeIndicEnumType fromValue(String v) {
        for (CrsMessageTypeIndicEnumType c: CrsMessageTypeIndicEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
