//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.25 at 08:55:55 AM UTC 
//


package ties.crs.v2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oecd.ties.crs.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oecd.ties.crs.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonPartyType }
     * 
     */
    public PersonPartyType createPersonPartyType() {
        return new PersonPartyType();
    }

    /**
     * Create an instance of {@link PersonPartyType.BirthInfo }
     * 
     */
    public PersonPartyType.BirthInfo createPersonPartyTypeBirthInfo() {
        return new PersonPartyType.BirthInfo();
    }

    /**
     * Create an instance of {@link NamePersonType }
     * 
     */
    public NamePersonType createNamePersonType() {
        return new NamePersonType();
    }

    /**
     * Create an instance of {@link CrsBodyType }
     * 
     */
    public CrsBodyType createCrsBodyType() {
        return new CrsBodyType();
    }

    /**
     * Create an instance of {@link CRSOECD }
     * 
     */
    public CRSOECD createCRSOECD() {
        return new CRSOECD();
    }

    /**
     * Create an instance of {@link MessageSpecType }
     * 
     */
    public MessageSpecType createMessageSpecType() {
        return new MessageSpecType();
    }

    /**
     * Create an instance of {@link AccountHolderType }
     * 
     */
    public AccountHolderType createAccountHolderType() {
        return new AccountHolderType();
    }

    /**
     * Create an instance of {@link ControllingPersonType }
     * 
     */
    public ControllingPersonType createControllingPersonType() {
        return new ControllingPersonType();
    }

    /**
     * Create an instance of {@link FIAccountNumberType }
     * 
     */
    public FIAccountNumberType createFIAccountNumberType() {
        return new FIAccountNumberType();
    }

    /**
     * Create an instance of {@link CorrectableAccountReportType }
     * 
     */
    public CorrectableAccountReportType createCorrectableAccountReportType() {
        return new CorrectableAccountReportType();
    }

    /**
     * Create an instance of {@link OrganisationINType }
     * 
     */
    public OrganisationINType createOrganisationINType() {
        return new OrganisationINType();
    }

    /**
     * Create an instance of {@link OrganisationPartyType }
     * 
     */
    public OrganisationPartyType createOrganisationPartyType() {
        return new OrganisationPartyType();
    }

    /**
     * Create an instance of {@link CorrectableOrganisationPartyType }
     * 
     */
    public CorrectableOrganisationPartyType createCorrectableOrganisationPartyType() {
        return new CorrectableOrganisationPartyType();
    }

    /**
     * Create an instance of {@link PaymentType }
     * 
     */
    public PaymentType createPaymentType() {
        return new PaymentType();
    }

    /**
     * Create an instance of {@link PersonPartyType.BirthInfo.CountryInfo }
     * 
     */
    public PersonPartyType.BirthInfo.CountryInfo createPersonPartyTypeBirthInfoCountryInfo() {
        return new PersonPartyType.BirthInfo.CountryInfo();
    }

    /**
     * Create an instance of {@link NamePersonType.FirstName }
     * 
     */
    public NamePersonType.FirstName createNamePersonTypeFirstName() {
        return new NamePersonType.FirstName();
    }

    /**
     * Create an instance of {@link NamePersonType.MiddleName }
     * 
     */
    public NamePersonType.MiddleName createNamePersonTypeMiddleName() {
        return new NamePersonType.MiddleName();
    }

    /**
     * Create an instance of {@link NamePersonType.NamePrefix }
     * 
     */
    public NamePersonType.NamePrefix createNamePersonTypeNamePrefix() {
        return new NamePersonType.NamePrefix();
    }

    /**
     * Create an instance of {@link NamePersonType.LastName }
     * 
     */
    public NamePersonType.LastName createNamePersonTypeLastName() {
        return new NamePersonType.LastName();
    }

    /**
     * Create an instance of {@link CrsBodyType.ReportingGroup }
     * 
     */
    public CrsBodyType.ReportingGroup createCrsBodyTypeReportingGroup() {
        return new CrsBodyType.ReportingGroup();
    }

}
