//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.25 at 08:55:55 AM UTC 
//


package ties.crs.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import ties.commontypesfatcacrs.v2.MonAmntType;


/**
 * <p>Java class for Payment_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payment_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Type" type="{urn:oecd:ties:crs:v2}CrsPaymentType_EnumType"/&gt;
 *         &lt;element name="PaymentAmnt" type="{urn:oecd:ties:commontypesfatcacrs:v2}MonAmnt_Type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payment_Type", propOrder = {
    "type",
    "paymentAmnt"
})
public class PaymentType {

    @XmlElement(name = "Type", required = true)
    @XmlSchemaType(name = "string")
    protected CrsPaymentTypeEnumType type;
    @XmlElement(name = "PaymentAmnt", required = true)
    protected MonAmntType paymentAmnt;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CrsPaymentTypeEnumType }
     *     
     */
    public CrsPaymentTypeEnumType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrsPaymentTypeEnumType }
     *     
     */
    public void setType(CrsPaymentTypeEnumType value) {
        this.type = value;
    }

    /**
     * Gets the value of the paymentAmnt property.
     * 
     * @return
     *     possible object is
     *     {@link MonAmntType }
     *     
     */
    public MonAmntType getPaymentAmnt() {
        return paymentAmnt;
    }

    /**
     * Sets the value of the paymentAmnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonAmntType }
     *     
     */
    public void setPaymentAmnt(MonAmntType value) {
        this.paymentAmnt = value;
    }

}
