name: Scan with Detekt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 0 * * 3'

  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Run Detekt
      uses: gradle/gradle-build-action@v1.5.0
      with:
        arguments: detektAll
        distributions-cache-enabled: true
        dependencies-cache-enabled: true
      env:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=--illegal-access=permit"
        ORG_GRADLE_PROJECT_HelloGithubPackageUsername: ${{ github.actor }}
        ORG_GRADLE_PROJECT_HelloGithubPackagePassword: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ github.workspace }}/build/reports/detekt/detekt.sarif
        checkout_path: ${{ github.workspace }}
