name: Scan with Detekt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 0 * * 3'

  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Run Detekt
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: detektAll
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
      continue-on-error: true
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ github.workspace }}/build/reports/detekt/detekt.sarif
        checkout_path: ${{ github.workspace }}
