name: Continuous Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11, 15 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - uses: actions/cache@v2.1.5
        name: gralde build cache
        with:
          path: |
            ~/.gradle/caches/build-cache-1
          key: ${{ runner.os }}-gradle-build-cache-${{ matrix.java-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-build-cache-${{ matrix.java-version }}-${{ github.sha }}
            ${{ runner.os }}-gradle-build-cache-${{ matrix.java-version }}-
            ${{ runner.os }}-gradle-build-cache-
      - uses: actions/cache@v2.1.5
        name: gralde cache
        with:
          path: |
            ~/.gradle/jdks
            ~/.gradle/nodejs
            ~/.gradle/yarn
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*') }}
            ${{ runner.os }}-gradle-cache-
      - uses: actions/cache@v2.1.5
        name: gralde kotlin js
        with:
          path: |
            build/js
          key: ${{ runner.os }}-gradle-kotlinjs-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-kotlinjs-
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check --stacktrace
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
