name: Continuous Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11 ]
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check --scan
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=--illegal-access=permit"
          ORG_GRADLE_PROJECT_HelloGithubPackageUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_HelloGithubPackagePassword: ${{ secrets.GITHUB_TOKEN }}
