name: Continuous Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: actions/cache@v2
        name: gralde build cache
        with:
          path: |
            ~/.gradle/caches/build-cache-1
          key: ${{ runner.os }}-gradle-build-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-build-cache-${{ github.sha }}
            ${{ runner.os }}-gradle-build-cache-
      - uses: actions/cache@v2
        name: gralde kotlin js
        with:
          path: |
            build/js
          key: ${{ runner.os }}-gradle-kotlinjs-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-kotlinjs-
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
