name: Continuous Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: actions/cache@v2
        name: gradle wrapper
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - uses: actions/cache@v2
        name: gralde cache
        with:
          path: |
            ~/.gradle/caches/module-2
            ~/.gradle/caches/build-cache-1
            ~/.gradle/jdks
            ~/.gradle/nodejs
            ~/.gradle/yarn
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - uses: actions/cache@v2
        name: gralde kotlin js
        with:
          path: |
            build/js
          key: ${{ runner.os }}-gradle-kotlinjs-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-kotlinjs-
      - run: ./gradlew check
